matrix:

- name: py
  sources:
  - '**/*.py'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - spell_check/spell_ignore_py.txt
  pipeline:
  - pyspelling.filters.python:
      comments: false

- name: markdown
  pipeline:
  - pyspelling.filters.text
  sources:
  - '**/*.md'
  aspell:
    lang: en
  dictionary:
    wordlists:
    - spell_check/spell_ignore_md.txt
  default_encoding: utf-8